
version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: .
    command: ["node", "src/server.js"]
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "3001:3001"
  worker:
    build: .
    command: ["node", "src/worker.js"]
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
